fix e2e auth setup after changes to the a0 login page (#1168)
This fixes some issues I was seeing on e2e tests that were failing due
to changes on the Auth0 login page. This change makes the selector
specific enough to hopefully not need more fixes in the future!

Example failure: 
```
   Error: locator.fill: Error: strict mode violation: getByLabel('Password') resolved to 2 elements:
        1) <input required="" id="password" name="password" type="password" spellcheck="false" aria-required="true" autocapitalize="none" autocomplete="current-password" aria-labelledby="password-label" class="input cad736208 c8df1647e"/> aka getByRole('textbox', { name: 'Password' })
        2) <button type="button" role="switch" aria-checked="false" data-action="toggle" aria-label="Show password" class="c4b96dbd3 ulp-button-icon js-required c58baf5af _button-icon">…</button> aka getByRole('switch', { name: 'Show password' })

    Call log:
      - waiting for getByLabel('Password')


      10 |
      11 |     await page.getByLabel('Email address').fill(process.env.E2E_TEST_USER);
    > 12 |     await page.getByLabel('Password').fill(process.env.E2E_TEST_PASSWORD);
         |                                       ^
      13 |     await page.getByRole('button', { name: 'Continue', exact: true }).click();
      14 |
      15 |     await expect(page).toHaveURL(/.*\/thread\/msg_A8E5H1X2O3/, { timeout: 20_000 });
        at /__w/olmo-ui/olmo-ui/e2e/auth-flow.ts:12:39
        ```